# Site title and description
title: Octocat's homepage
description: Bookmark this to keep an eye on my project updates!

# Jekyll theme to use
theme: jekyll-theme-minimal

# URL of your site (leave empty if using GitHub Pages)
url: ""

# Markdown processor
markdown: kramdown
