title: "Lorenzo Niccoli"
description: "Postdoc @ ETH"

url: ""

remote_theme: academicpages/academicpages@master

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge
