title: "Lorenzo Niccoli"
description: "Postdoc @ ETH"

url: ""

remote_theme: academicpages/academicpages

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge


# ADDITIONAL SETTINGS
# favicon: /assets/images/favicon.ico
# google_analytics: UA-XXXXXXXXX-X
